<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <InternalsVisibleTo Include="EnviousWispr.Architecture.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EnviousWispr.Core\EnviousWispr.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio.Wasapi" Version="3.0.1" />
  </ItemGroup>
</Project>
