namespace EnviousWispr.Core.Errors;

public enum AppErrorCode
{
    InvalidData,
    NewerSchema,
    StorageUnavailable,
    AccessDenied,
    Cancelled,
    PreviousRunInterrupted,
    SessionTimedOut,
    LowDiskSpace,
    LowMemory,
    InvalidTransition,
    AudioDeviceUnavailable,
    AudioDeviceLost,
    AudioFormatUnsupported,
    CaptureAlreadyActive,
    HotkeyInvalid,
    HotkeyConflict,
    HotkeyUnavailable,
    TargetUnavailable,
    HardwareProbeFailed,
    RuntimeProviderUnavailable,
    RuntimeProviderIncompatible,
    ModelPackUnavailable,
    RuntimeWorkerFailed,
    RuntimeResourceBusy,
    TranscriptionFailed,
    PolishProviderUnavailable,
    PolishInputTooLarge,
    PolishTimedOut,
    PolishFailed,
    PolishCredentialMissing,
    PolishCredentialUnreadable,
    PolishApiKeyRejected,
    PolishAccessDenied,
    PolishQuotaExceeded,
    PolishRateLimited,
    PolishModelUnavailable,
    PolishContentBlocked,
    PolishProviderServerError,
    PolishBadRequest,
    PolishEmptyResponse,
    PolishOutputTruncated,
    PolishEndpointInvalid,
    PolishRemoteModelDisallowed,
    DeliveryTargetChanged,
    DeliveryProtectedField,
    DeliveryElevatedTarget,
    DeliveryUnsupportedTarget,
    DeliveryClipboardUnavailable,
    DeliveryInputBlocked,

    // EACH WAY A DELIVERY ENDS WITHOUT THE WORDS LANDING KEEPS ITS OWN NAME (plan-2 step 13); these
    // five used to be logged as DeliveryUnsupportedTarget, which is a policy refusal, not any of them.
    DeliveryAccessibilityUnavailable,
    DeliveryUnverified,
    DeliveryCancelled,
    DeliveryDisposed,
    DeliveryFaulted,
}

public enum AppErrorStage
{
    Session,
    SettingsLoad,
    SettingsSave,
    SettingsReset,
    ProfileImport,
    ProfileExport,
    HistoryLoad,
    HistorySave,
    RunState,
    RecoveryText,
    ResourceHealth,
    SystemLifecycle,
    AudioDeviceEnumeration,
    AudioCapture,
    HotkeyConfiguration,
    HotkeyHook,
    TargetCapture,
    HardwareDiscovery,
    RuntimeSelection,
    RuntimeWorker,
    RuntimeResource,
    FinalAsr,
    LocalPolish,
    CloudPolish,
    CredentialStore,
    ContextRead,
    TextDelivery,
    DiagnosticExport,
}

public sealed record AppError(AppErrorCode Code, AppErrorStage Stage, bool CanRetry);
